#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-service-operaton
  sql:
    init:
      mode: always
operaton.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
scheduler:
  logger-worker:
    cron: "*/5 * * * * *"
